import { StyleSheet } from 'react-native';
import { colors, fonts } from '../styles';

const style = StyleSheet.create({
  container: {
    flex: 1, // <-- This is the key fix!
    padding: 24,
    justifyContent: 'flex-start',
    paddingBottom: 40,
  },
  imagePreview: {
    width: '100%',
    height: 250,
    resizeMode: 'contain',
    marginBottom: 20,
    borderRadius: 20,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderWidth: 2,
    borderColor: colors.green,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  headerText: {
    fontFamily: fonts.heading,
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.accent,
    textAlign: 'center',
    marginBottom: 18,
    letterSpacing: 1,
    textShadowColor: colors.shadow,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  resultText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: colors.green,
    marginBottom: 12,
    lineHeight: 24,
    fontWeight: '500',
  },
  confidenceText: {
    fontFamily: fonts.body,
    fontSize: 16,
    color: colors.text,
    marginBottom: 10,
    fontStyle: 'italic',
    opacity: 0.9,
  },
  divider: {
    height: 1,
    marginVertical: 10,
    opacity: 0.7,
  },
  analysisContainer: {
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.green,
    marginBottom: 24,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  errorText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: '#FF5252',
    marginTop: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  loader: {
    marginTop: 20,
  },
  backButton: {
    marginTop: 20,
    marginBottom: 10,
    padding: 12,
    borderRadius: 10,
    alignItems: 'center',
    elevation: 3,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
  },
  buttonText: {
    fontFamily: fonts.body,
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    letterSpacing: 1,
  },
  text: {
    fontFamily: fonts.body,
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
    opacity: 0.95,
  },
});

export default style;
