import { StyleSheet } from 'react-native';
import { colors, fonts } from '../styles';

const style = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    paddingBottom: 40,
  },
  imagePreview: {
    width: '100%',
    height: 250,
    resizeMode: 'contain',
    marginBottom: 20,
    borderRadius: 20,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderWidth: 2,
    borderColor: colors.green,
    backgroundColor: colors.card,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  headerText: {
    fontFamily: fonts.heading,
    fontSize: 26,
    fontWeight: 'bold',
    color: colors.heading,
    textAlign: 'center',
    marginBottom: 18,
    letterSpacing: 1,
    textShadowColor: colors.shadow,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  resultText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: colors.green,
    marginBottom: 12,
    lineHeight: 24,
    fontWeight: '500',
    textAlign: 'left',
  },
  confidenceText: {
    fontFamily: fonts.body,
    fontSize: 16,
    color: colors.text,
    marginBottom: 10,
    fontStyle: 'italic',
    opacity: 0.9,
    textAlign: 'left',
  },
  divider: {
    height: 1,
    backgroundColor: colors.green,
    marginVertical: 10,
    opacity: 0.7,
  },
  analysisContainer: {
    backgroundColor: 'transparent',
    paddingVertical: 0,
    paddingHorizontal: 0,
    borderRadius: 0,
    borderWidth: 0,
    marginBottom: 18,
    shadowColor: 'transparent',
    alignSelf: 'stretch',
  },
  dropdownHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 0,
    width: '100%',
  },
  dropdownHeaderText: {
    fontFamily: fonts.body,
    fontSize: 17,
    color: colors.heading,
    fontWeight: 'bold',
    textAlign: 'left',
    flex: 1,
  },
  dropdownIcon: {
    marginLeft: 8,
  },
  dropdownContent: {
    paddingLeft: 2,
    paddingRight: 0,
    paddingBottom: 8,
    color: colors.text,
    fontSize: 15,
    textAlign: 'left',
  },
  errorText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: '#FF5252',
    marginTop: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  loader: {
    marginTop: 20,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 22,
    padding: 18,
    marginVertical: 24,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
    alignItems: 'stretch',
    width: '100%',
    maxWidth: 420,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
    gap: 6,
    backgroundColor: colors.green,
  },
  buttonText: {
    fontFamily: fonts.body,
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.heading,
    letterSpacing: 1,
  },
  text: {
    fontFamily: fonts.body,
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
    opacity: 0.95,
    textAlign: 'left',
  },
});

export default style;
