import { StyleSheet } from 'react-native';
import { colors, fonts } from '../styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    fontFamily: fonts.heading,
    fontSize: 26,
    color: colors.heading,
    marginVertical: 12,
    backgroundColor: 'transparent',
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: colors.shadow,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  noImages: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: colors.text,
    margin: 20,
    textAlign: 'center',
    opacity: 0.8,
  },
  image: {
    width: 100,
    height: 100,
    margin: 5,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.green,
  },
  plusIcon: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.accent,
    borderRadius: 10,
    margin: 5,
    backgroundColor: colors.card,
  },
  uploadButton: {
    backgroundColor: colors.green,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    marginVertical: 20,
    alignSelf: 'center',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  uploadText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: colors.heading,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(38, 50, 56, 0.97)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 40,
    left: 20,
  },
  fullImage: {
    width: '90%',
    height: '70%',
    marginVertical: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.green,
    backgroundColor: colors.card,
  },
  analyzeButton: {
    backgroundColor: colors.accent,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 10,
    marginVertical: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  analyzeText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: colors.card,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  fixedHeader: {
    fontFamily: fonts.heading,
    fontSize: 24,
    color: colors.accent,
    marginVertical: 10,
    textAlign: 'center',
    backgroundColor: colors.card,
    padding: 10,
    width: '100%',
    position: 'absolute',
    top: 0,
    zIndex: 1,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 2,
  },
  lowerHalf: {
    flex: 1,
    width: '100%',
    paddingTop: 40,
  },
  blurredBackground: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
    opacity: 0.9,
  },
  plusIconText: {
    position: 'absolute',
    color: colors.accent,
    fontWeight: 'bold',
    fontSize: 32,
  },
});

export default styles;